package compare

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/0xCHANDA/womm/internal/core"
)

// The differential corpus is generated by testdata/node-semver-corpus.gen.js
// against a real node-semver (the version is recorded in the file). Node
// is research tooling only: the test itself needs no Node runtime.
type differentialCorpus struct {
	NodeSemver string `json:"nodeSemver"`
	Cases      []struct {
		Range                      string  `json:"range"`
		Version                    string  `json:"version"`
		ValidRange                 *string `json:"validRange"`
		Satisfies                  *bool   `json:"satisfies"`
		SatisfiesIncludePrerelease *bool   `json:"satisfiesIncludePrerelease"`
	} `json:"cases"`
}

// TestDifferentialAgainstNodeSemver pins WOMM's contract against the
// authoritative implementation, without requiring WOMM to reproduce
// every npm expression:
//
//   - WOMM never says PASS where node-semver says the range is invalid;
//   - WOMM never says PASS where neither node-semver's default nor its
//     includePrerelease mode is satisfied (no false PASS, whichever
//     consumer semantics apply);
//   - WOMM never says FAIL where both modes are satisfied (no false
//     FAIL for release-only disagreements);
//   - for release versions and ranges both sides accept, WOMM's verdict
//     equals node-semver's (the two modes agree there).
//
// UNKNOWN (an explicit refusal) is always allowed.
func TestDifferentialAgainstNodeSemver(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "node-semver-corpus.json"))
	if err != nil {
		t.Fatal(err)
	}
	var corpus differentialCorpus
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	if len(corpus.Cases) < 1000 {
		t.Fatalf("corpus has only %d cases; regenerate it", len(corpus.Cases))
	}
	t.Logf("node-semver %s, %d cases", corpus.NodeSemver, len(corpus.Cases))

	var pass, fail, unknown int
	for _, c := range corpus.Cases {
		req := core.Requirement{Name: "node", Constraint: c.Range}
		obs := core.Observation{Name: "node", Present: true, Version: c.Version}
		m, cerr := Compare(req, obs)
		switch m.Status {
		case core.StatusUnknown:
			unknown++
			continue
		case core.StatusPass:
			pass++
		case core.StatusFail:
			fail++
		default:
			t.Fatalf("%q vs %q: status %q", c.Range, c.Version, m.Status)
		}
		if cerr != nil {
			t.Fatalf("%q vs %q: verdict %q with error %v", c.Range, c.Version, m.Status, cerr)
		}
		if c.Satisfies == nil {
			// node-semver considers the version itself invalid; WOMM
			// must have refused it (strict semver) — it did not.
			t.Errorf("%q vs %q: WOMM %q but node-semver cannot parse the version", c.Range, c.Version, m.Status)
			continue
		}
		sat, satPre := *c.Satisfies, *c.SatisfiesIncludePrerelease
		if c.ValidRange == nil && m.Status == core.StatusPass {
			t.Errorf("%q vs %q: PASS but node-semver rejects the range", c.Range, c.Version)
		}
		if m.Status == core.StatusPass && !sat && !satPre {
			t.Errorf("%q vs %q: FALSE PASS (node-semver: false in both modes)", c.Range, c.Version)
		}
		if m.Status == core.StatusFail && sat && satPre {
			t.Errorf("%q vs %q: FALSE FAIL (node-semver: true in both modes)", c.Range, c.Version)
		}
		if c.ValidRange != nil && sat == satPre {
			want := core.StatusFail
			if sat {
				want = core.StatusPass
			}
			if m.Status != want {
				t.Errorf("%q vs %q: WOMM %q, node-semver %v (both modes)", c.Range, c.Version, m.Status, sat)
			}
		}
	}
	t.Logf("verdicts: pass=%d fail=%d unknown=%d", pass, fail, unknown)
	if pass == 0 || fail == 0 {
		t.Fatal("corpus exercised no verdicts")
	}
}

func TestDifferentialCorpusCoversInvalidObservedVersions(t *testing.T) {
	// Sanity: WOMM's strict version parse must refuse what node-semver
	// refuses, and vice versa for the corpus versions.
	for _, v := range []string{"24.7.0", "24.7.0-beta.1", "24.7.0+build.1"} {
		m, err := Compare(core.Requirement{Name: "node", Constraint: "*"}, core.Observation{Name: "node", Present: true, Version: v})
		if err != nil && !errors.Is(err, ErrPrereleaseRange) {
			t.Errorf("%q: %v", v, err)
		}
		_ = m
	}
}
