#!/bin/sh
# check-commit-attribution.sh — verify commit authorship before merging.
#
# Inspects every commit in <base>..<head> and fails when:
#   - author/committer does not match the repository owner identity
#     (owner's configured email or the owner's GitHub noreply alias);
#     committer "GitHub <noreply@github.com>" is allowed only with an
#     owner author (GitHub web UI: merge button / web editor);
#   - any attribution trailer is present ("Co-Authored-By: Claude",
#     any noreply@anthropic.com, "Generated with/by ...", Anthropic).
#
# Portable POSIX sh. Read-only: never modifies the repository.
# Usage:
#   scripts/check-commit-attribution.sh [base-ref] [head-ref]
# Defaults: base = origin/main, head = HEAD.

set -u

BASE=${1:-origin/main}
HEAD=${2:-HEAD}
OWNER_NAME=0xCHANDA
# Owner's GitHub noreply alias. Public repo information; the GitHub UI
# uses it as the author identity of merge/web commits. Update only with
# evidence that the account changed.
OWNER_NOREPLY=68290193+0xCHANDA@users.noreply.github.com
OWNER_EMAIL="$(git config --get user.email || true)"

if [ -z "$OWNER_EMAIL" ]; then
    echo "error: no user.email configured; cannot define the expected identity" >&2
    exit 2
fi

if ! git rev-parse --verify --quiet "$BASE" >/dev/null 2>&1; then
    echo "error: base ref not found: $BASE (try: git fetch origin)" >&2
    exit 2
fi
if ! git rev-parse --verify --quiet "$HEAD" >/dev/null 2>&1; then
    echo "error: head ref not found: $HEAD" >&2
    exit 2
fi

range="${BASE}..${HEAD}"
if [ -z "$(git rev-list "$range")" ]; then
    echo "no commits in ${range} — nothing to check"
    exit 0
fi

echo "base: ${BASE}  head: ${HEAD}  expected author email: (configured owner identity)"
fail=0

for sha in $(git rev-list "$range"); do
    short=$(git show -s --format=%h "$sha")
    subject=$(git show -s --format=%s "$sha")
    ae=$(git show -s --format=%ae "$sha")
    an=$(git show -s --format=%an "$sha")
    cn=$(git show -s --format=%cn "$sha")
    ce=$(git show -s --format=%ce "$sha")
    an_ok(){
        case "$ae" in
            "$OWNER_EMAIL"|"$OWNER_NOREPLY") return 0 ;;
        esac
        return 1
    }
    cm_ok(){
        case "$cn|$ce" in
            "$OWNER_NAME|$OWNER_EMAIL") return 0 ;;
            "GitHub|$OWNER_NOREPLY") return 0 ;;
            "GitHub|noreply@github.com") return 0 ;;
        esac
        return 1
    }
    if an_ok && cm_ok; then
        printf 'ok      %s %s\n' "$short" "$subject"
    else
        printf 'BAD     %s %s\n' "$short" "$subject"
        printf '        author=%s <%s> committer=%s <%s>\n' "$an" "$ae" "$cn" "$ce"
        fail=1
    fi

    if git show -s --format=%B "$sha" | grep -iq \
        'co-authored-by\|noreply@anthropic\.com\|anthropic\|generated with\|generated by'; then
        printf 'TRAILER %s %s\n' "$short" "$subject"
        fail=1
    fi
done

if [ "$fail" = 1 ]; then
    echo "FAIL: attribution problems above (${range}); do not merge. See docs/agent-workflow.md." >&2
    exit 1
fi
echo "PASS: all commits in ${range} attributed correctly."
exit 0
